import { test, expect } from 'playwright/test'

/**
 * Proves the Batch 4.5 asset pipeline end to end: a .glb generated by headless
 * Blender, loaded by an agent-authored R3F component, actually rendering.
 *
 * Deliberately does NOT assert on the DOM alone. A canvas element mounts
 * whether or not WebGL produced anything, and a failed .glb parse leaves the
 * Suspense fallback up with the page looking otherwise fine — both of which
 * would pass a "does the element exist" test. The assertions below read pixels
 * instead, because pixels are the only thing that can distinguish "rendered"
 * from "mounted".
 */
const EMAIL = process.env.E2E_EMAIL
const PASSWORD = process.env.E2E_PASSWORD

test.describe('artifact lab', () => {
  // Every route is behind the owner gate (src/proxy.ts matches everything but
  // /login and /api), so this needs a real login for the same reason the
  // terminal sizing test does. Skips rather than fails without credentials.
  test.skip(!EMAIL || !PASSWORD, 'Set E2E_EMAIL and E2E_PASSWORD (owner account) to run the artifact lab test.')

  test('renders the Blender-generated model and animates it', async ({ page }) => {
    const failures: string[] = []
    page.on('pageerror', (e) => failures.push(e.message))

    await page.goto('/login')
    await page.getByPlaceholder('email').fill(EMAIL!)
    await page.getByPlaceholder('password').fill(PASSWORD!)
    await page.getByRole('button', { name: /sign in|log in|continue/i }).first().click()
    await page.waitForURL((url) => !url.pathname.startsWith('/login'), { timeout: 30_000 })

    await page.goto('/atelier/lab')

    const canvas = page.locator('canvas')
    await expect(canvas).toBeVisible()
    await expect(canvas).toHaveAttribute('data-artifact-ready', 'true', { timeout: 20_000 })

    // The .glb must have been fetched and parsed — a 404 here is the most
    // likely real failure and it is otherwise silent.
    const modelResponse = await page.request.get('/assets/golem-cube.glb')
    expect(modelResponse.status()).toBe(200)
    const bytes = await modelResponse.body()
    expect(bytes.subarray(0, 4).toString('ascii')).toBe('glTF')

    // Give the loader time to resolve and the first frames to land.
    await page.waitForTimeout(3_000)

    const sample = async () =>
      canvas.screenshot().then((b) => b.toString('base64'))

    const first = await sample()

    // A blank canvas compresses to almost nothing; a rendered 3D scene does
    // not. This catches a context that initialised but drew no geometry.
    expect(Buffer.from(first, 'base64').byteLength).toBeGreaterThan(5_000)

    // Rotation means consecutive frames differ. A static image here would mean
    // the model loaded but useFrame never ran.
    await page.waitForTimeout(1_200)
    const second = await sample()
    expect(second).not.toBe(first)

    expect(failures, `page errors: ${failures.join(' | ')}`).toHaveLength(0)
  })
})
