import { test, expect } from 'playwright/test'

/**
 * Proves the mission dashboard renders real rows from the live database.
 *
 * The one failure mode worth guarding against here is a page that looks
 * populated while showing nothing real — a fixture, a hardcoded example row, a
 * spinner that never resolves. So the assertions key on data this page cannot
 * invent: a mission repo slug minted by an earlier verification run, and the
 * Layer 3 validator agents seeded in Batch 1.
 */
const EMAIL = process.env.E2E_EMAIL
const PASSWORD = process.env.E2E_PASSWORD

test.describe('missions dashboard', () => {
  // Everything but /login and /api is behind the owner gate in src/proxy.ts.
  test.skip(!EMAIL || !PASSWORD, 'Set E2E_EMAIL and E2E_PASSWORD (owner account) to run the missions dashboard test.')

  test('lists real missions, tasks and agents', async ({ page }) => {
    await page.goto('/login')
    await page.getByRole('button', { name: 'email', exact: true }).click()
    await page.locator('button[type="button"]', { hasText: /^sign in$/ }).first().click()
    await page.getByPlaceholder('email').fill(EMAIL!)
    await page.getByPlaceholder('password').fill(PASSWORD!)
    await page.locator('button[type="submit"]').click()
    await page.waitForURL((url) => !url.pathname.startsWith('/login'), { timeout: 60_000 })

    await page.goto('/missions')

    // A mission whose repo slug was generated by verify-scheduler.mjs. No
    // mock could produce this string — it carries the run's own timestamp.
    const mission = page.locator('button', { hasText: /verify\/scheduler-\d+/ }).first()
    await expect(mission).toBeVisible({ timeout: 30_000 })

    // The roster, including the Layer 3 agents this batch's validators map to.
    await expect(page.getByRole('cell', { name: 'Type Checker' })).toBeVisible()
    await expect(page.getByRole('cell', { name: 'Claude Code' })).toBeVisible()

    // Detection state is the thing that used to need a script to answer.
    await expect(page.getByRole('cell', { name: /claude --permission-mode/ })).toBeVisible()

    // Opening a mission loads its task graph from /api/missions/[id].
    await mission.click()
    const taskPanel = page.locator('section', { hasText: /^tasks/ }).first()
    await expect(taskPanel.getByText(/priority:/).first()).toBeVisible({ timeout: 30_000 })

    // At least one task must show a real pipeline status rather than a
    // placeholder. 'complete' is the one Batch 5 made reachable.
    await expect(page.getByText(/^(pending|assigned|running|validating|complete|failed|blocked)$/i).first()).toBeVisible()
  })
})
